--
-- cosmo sound hardware
--
-- The original hardware runs with a 333Khz clock
-- and feeds the output though a resistor to the amp 

-- This is way too quick for a sample rate of 96Khz
-- so I have slowed it down to 192Khz

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.std_logic_unsigned.all;
  use ieee.numeric_std.all;

entity COSMO_SFX is
  port (
    CLK               : in  std_logic;
	 PORT0_WR          : in  std_logic;
	 PORT1_WR          : in  std_logic;
	 PORT0				 : in  std_logic_vector(6 downto 0);
	 PORT1				 : in  std_logic_vector(6 downto 0);
	 PORT2				 : in  std_logic_vector(6 downto 0);
	 PORT7				 : in  std_logic_vector(6 downto 0);
	 --
	 dn_addr    		 : in  std_logic_vector(15 downto 0);
	 dn_data    		 : in  std_logic_vector(7 downto 0);
	 dn_wr      		 : in  std_logic;
	 dn_ld	     		 : in  std_logic;
	 --
	 audio_enabled		 : in  std_logic;
	 O_SFX				 : out std_logic_vector(7 downto 0)
    );
end;

architecture RTL of COSMO_SFX is

signal ClockCount  : natural range 0 to 127;
signal WaveCount   : natural range 0 to 255;
signal Clk_en      : std_logic;
signal Wav_en      : std_logic;

signal Count4D     : std_logic_vector(14 downto 0);
signal LastCount4D : std_logic_vector(14 downto 0);

-- Channel 1
signal Clear7D    : std_logic;
signal Count7D    : std_logic_vector(7 downto 0);
signal Count9D    : std_logic_vector(7 downto 0);
signal Latch_11DA : std_logic;
signal Output1    : std_logic_vector(1 downto 0);
signal Rom7D_addr : std_logic_vector(10 downto 0);
signal data_7D    : std_logic_vector(7 downto 0);

-- Channel 2
signal Clear6E    : std_logic;
signal Count6E    : std_logic_vector(7 downto 0);
signal Count8E    : std_logic_vector(7 downto 0);
signal Latch_11DB : std_logic;
signal Output2    : std_logic_vector(1 downto 0);
signal Rom6E_addr : std_logic_vector(10 downto 0);
signal data_6E    : std_logic_vector(7 downto 0);


begin

	------------
	-- Clocks --
	------------

	-- Clock is generated by NE555V (1E) output should be 333Khz
	-- This is fed to 4D and FREQ/256 onwards to 1D to generate successive "divide by two" versions from FREQ/2 to FREQ/32768 
	
	-- so Count4D(0) = FREQ/2 ... Count4D(14) = FREQ/32768

	process (CLK)
	begin
	
		if rising_edge(CLK) then
		
			-- Main counter (4D) increments at 192khz (original is 333Khz)
			if ClockCount = 127 then
				ClockCount <= 0;				
				Count4D    <= Count4D + 1;
				Clk_en     <= '1';
			else
				ClockCount <= ClockCount + 1;
				Clk_en     <= '0';
			end if;
			
			-- Wave Clock outputs data at 96Khz
			if WaveCount = 255 then
				WaveCount <= 0;				
				Wav_en     <= '1';
			else
				WaveCount <= WaveCount + 1;
				Wav_en     <= '0';
			end if;
		end if;

	end process;

	process (CLK)
		variable Off7D    : integer range 0 to 15;	
		variable Off9D    : integer range 0 to 15; 
		variable Off4EA   : integer range 0 to 7; 
		variable SOUNDA   : std_logic;
		
		variable Off6E    : integer range 0 to 15; 
		variable Off8E    : integer range 0 to 15; 
		variable Off4EB   : integer range 0 to 7; 
		variable SOUNDB   : std_logic;
	begin
		if rising_edge(CLK) then

			-- These happen under CPU clock, so check frequently
		
			-- Clear 7D - Counter is restarted on access to port 0
			if PORT0_WR = '1' then
				Clear7D <= '1';
			end if;

			-- Clear 6E - Counter is restarted on access to port 1
			if PORT1_WR = '1' then
				Clear6E <= '1';
			end if;	

			-- This is the actual sound circuit, so run at proper frequency
			
			if Clk_en = '1' then
			
				------------------------
				-- Channel 1 (rom 7D) --
				------------------------
				
				-- increment address at selected frequency, stop if at end
				
				Off7D := 7 + to_integer(unsigned(PORT0(6 downto 4))); -- port 0 4-6 = speed
				if Clear7D='1' or data_7D = "00000000" then
					Count7D <= (others => '0');
					Clear7D <= '0';
				elsif (LastCount4D(Off7D) = '0' and Count4D(Off7D) = '1') and Count7D /= "11111111" then
					Count7D <= Count7D + '1';
				end if;

				-- Get speed to increment channel loop counter

				Off9D := 4 + to_integer(unsigned(PORT7(2 downto 0))); -- port 7 0-2 = speed
				if Count4D(Off9D) = '1' or Off9D=7 then
					Off4EA := 1; -- 1;
				else
					Off4EA := 2; -- 2;
				end if;

				if (LastCount4D(Off4EA) = '0' and Count4D(Off4EA) = '1') then
					if Count9D = "11111111" then
						 Count9D <= data_7D;
					    if data_7D /= "11111111" then
							Latch_11DA <= not Latch_11DA;
						 end if;
					else
						 Count9D <= Count9D + '1';
					end if;
				end if;
				
				-- No sound at end (stays there for silence)
				
				if Count9D = "11111111" then
					SOUNDA := '0';
				else
					case PORT7(6 downto 4) is
						when "000" => SOUNDA := Latch_11DA;
						when "001" => SOUNDA := Count9D(1);
						when "010" => SOUNDA := Count9D(2);
						when "011" => SOUNDA := Count9D(3);
						when "100" => SOUNDA := Count9D(4);
						when "101" => SOUNDA := Count9D(5);
						when "110" => SOUNDA := Count9D(6);
						when "111" => SOUNDA := Count9D(7);
					end case;
				end if;
				
				-- Add to output array
				
				Output1 <= Output1(0) & SOUNDA;


				------------------------
				-- Channel 2 (rom 6D) --
				------------------------

				-- increment address at selected frequency, stop if at end
				
				Off6E := 4 + to_integer(unsigned(PORT1(6 downto 4))); -- port 1 4-6 = speed
				if Clear6E='1' or data_6E = "00000000" then
					Count6E <= (others => '0');
					Clear6E <= '0';
				elsif (LastCount4D(Off6E) = '0' and Count4D(Off6E) = '1') and Count6E /= "11111111" then
					Count6E <= Count6E + '1';
				end if;

				-- Get speed to increment channel loop counter

				Off8E := 4 + to_integer(unsigned(PORT2(2 downto 0))); -- port 2 0-2 = speed
				if Count4D(Off8E) = '1' or Off8E=7 then
					Off4EB := 0; -- 0;
				else
					Off4EB := 1; -- 1;
				end if;

				if (LastCount4D(Off4EB) = '0' and Count4D(Off4EB) = '1') then
					if Count8E = "11111111" then
						 Count8E <= data_6E;
						 if data_6E /= "11111111" then
							Latch_11DB <= not Latch_11DB;
						 end if;
					else
						 Count8E <= Count8E + '1';
					end if;
				end if;
				
				-- No sound at end (stays there for silence)
				
				-- if Count9D = "11111111" or Count8E = "11111111" then
				if Count8E = "11111111" then
					SOUNDB := '0';
				else
					case PORT2(6 downto 4) is
						when "000" => SOUNDB := Latch_11DB;
						when "001" => SOUNDB := Count8E(1);
						when "010" => SOUNDB := Count8E(2);
						when "011" => SOUNDB := Count8E(3);
						when "100" => SOUNDB := Count8E(4);
						when "101" => SOUNDB := Count8E(5);
						when "110" => SOUNDB := Count8E(6);
						when "111" => SOUNDB := Count8E(7);
					end case;
				end if;
				
				-- Add to output array
				
				Output2 <= Output2(0) & SOUNDB;
				
				-- Control variables for next pass
				
				LastCount4D <= Count4D;
			end if;
	end if;
		
	end process;

	-- Output Sample data at 96Khz

	process (CLK)
		variable Bits : integer range 0 to 7; 
	begin
		if rising_edge(CLK) then
			if Wav_en = '1' then
			
				Bits := 0;
				for i in Output1'range loop
					if Output1(i) = '1' then Bits := Bits + 1; 
					end if;
					if Output2(i) = '1' then Bits := Bits + 1; 
					end if;
				end loop;			
			
				-- Convert to 8 bit value for DAC
				O_SFX <= std_logic_vector(to_unsigned((Bits * 24),8));
			
			end if;

		end if;
	end process;

	-----------------
	-- Rom Storage --
	-----------------
	
	-- Data for sound rom files for 7D and 6E
	
 Rom7D_addr <= dn_addr(10 downto 0) when dn_ld='1' else 
               PORT0(2 downto 0) & Count7D; -- port 0 0-2 = select FX page
	
 rom_7D : entity work.spram
	generic map (
	  addr_width_g => 11
	)
	port map (
	  q        => data_7D,
	  data     => dn_data(7 downto 0),
	  address  => Rom7D_addr,
	  wren     => dn_wr and dn_ld and not dn_addr(11),
	  clock    => CLK
   );
	
 Rom6E_addr <= dn_addr(10 downto 0) when dn_ld='1' else 
               PORT1(2 downto 0) & Count6E; -- port 1 0-2 = select FX page
	
 rom_6E : entity work.spram
	generic map (
	  addr_width_g => 11
	)
	port map (
	  q        => data_6E,
	  data     => dn_data(7 downto 0),
	  address  => Rom6E_addr,
	  wren     => dn_wr and dn_ld and dn_addr(11),
	  clock    => CLK
   );
	
end architecture RTL;
